#include "gprs.h"

typedef enum {
    INITIAL_STATUS, // AT
    CHECKING_IF_READY_TO_START,
    REQUESTING_SIGNAL_QUALITY, // AT+CSQ
    ANALYZING_SIGNAL_QUALITY,
    REQUESTING_NETWORK_REGISTRATION_STATUS, // AT+CREG?
    ANALYZING_NETWORK_REGISTRATION_STATUS,
    SETTING_FULL_OPERATION_MODE,  // AT+CFUN=1
    ANALYZING_FULL_OPERATION_MODE_VALUE,
    REQUESTING_SIM_AVAILABILITY, // AT+CPIN?
    ANALYZING_SIM_AVAILABILITY,
    REGISTERING_TO_APN, // AT+CSTT="<your_apn>","<user>","<password>"
    ANALYZING_APN_REGISTRATION,
    SETTING_INTERNET_PROTOCOL_CONTEXT, // AT+CIICR
    ANALYZING_INTERNET_PROTOCOL_CONTEXT,
    STABLISHING_REMOTE_SERVER_CONNECTION, // AT+CIPSTART="TCP","<server_public_ip>",">server_port>"
    ANALYZING_REMOTE_SERVER_CONNECTION,
    READY_TO_SEND_DATA,
    SENDING_DATA, // AT+CIPSEND
    CHECKING_IF_DATA_WAS_CORRECTLY_SENT,
    CLOSING_CONNECTION, // AT+CIPCLOSE
} gprs_state_t;